// import dataImg from './dataImg';
import dataImg from './images';

const filterWork = [
  {
    name: 'React',
    title: 'YouTube / копия',
    description: 'Полнофункциональное и полностью адаптивное SPA, YouTube клон с React JS, Tailwind CSS и Rapid Api.',
    linkGit: 'https://github.com/Webfre/clone-youtube',
    linkPage: 'https://webfre.github.io/clone-youtube/',
    imgUrl: dataImg.progect2,
    tags: ['React', 'Все'],
  },
  {
    name: 'React',
    title: 'Google / копия',
    description: ' Полнофункциональное и полностью отзывчивое адаптивное SPA, Google клон с React JS, Tailwind CSS и Google Search API.',
    linkGit: 'https://github.com/Webfre/google-search-clone-app',
    linkPage: 'https://webfre.github.io/google-search-clone-app/',
    imgUrl: dataImg.progect3,
    tags: ['React', 'Все'],
  },
  {
    name: 'React',
    title: 'Crypto / поиск',
    description: ' Приложение для отслеживания цен на криптовалютном рынке c React JS, React Hook, Axios, Cryptocurrency API.',
    linkGit: 'https://github.com/Webfre/crypto-finance-price',
    linkPage: 'https://webfre.github.io/crypto-finance-price/',
    imgUrl: dataImg.progect8,
    tags: ['React', 'Все'],
  },
  {
    name: 'React',
    title: 'TravelTour / путешествия',
    description: 'Отзывчивое  и полностью адаптивное SPA на React JS, библиотеки Aos (анимации), React Icons и видео-фона.',
    linkGit: 'https://github.com/Webfre/travel-tour',
    linkPage: 'https://webfre.github.io/travel-tour/',
    imgUrl: dataImg.progect5,
    tags: ['React', 'Все'],
  },
  {
    name: 'React',
    title: 'TravelAgency / все о турах',
    description: 'Отзывчивое и полностью адаптивное SPA, о турах и путешествиях на React JS, React Hook.',
    linkGit: 'https://github.com/Webfre/travel-agency',
    linkPage: 'https://webfre.github.io/travel-agency/#/',
    imgUrl: dataImg.progect4,
    tags: ['React', 'Все'],
  },
  {
    name: 'React',
    title: 'BGym / мир фитнеса',
    description: 'Полнофункциональное и полностью отзывчивое адаптивное SPA, на React JS, React Router Dom 6',
    linkGit: 'https://github.com/Webfre/website-fitness-app',
    linkPage: 'https://webfre.github.io/website-fitness-app/',
    imgUrl: dataImg.progect6,
    tags: ['React', 'Все'],
  },
  {
    name: 'React',
    title: 'Weather / прогноз сейчас',
    description: 'Приложение погоды с почасовым и ежедневным прогнозом на React JS, React Toastify и Tailwind CSS, используя OWM API.',
    linkGit: 'https://github.com/Webfre/weather-forecast',
    linkPage: 'https://webfre.github.io/weather-forecast/',
    imgUrl: dataImg.progect1,
    tags: ['React', 'Все'],
  },
  {
    name: 'React',
    title: 'Todo / дела под контролем',
    description: 'Список задач с интересным дизайном для создания, добавления, редактирования и удаления заметки в любое время.',
    linkGit: 'https://github.com/Webfre/todo-list',
    linkPage: 'https://webfre.github.io/todo-list/',
    imgUrl: dataImg.progect7,
    tags: ['React', 'Все'],
  },
  {
    name: 'React',
    title: 'NFT / будь уникальным',
    description: 'Приложение NFT под торговую площадку c React JS, CSS in JS styled-components.',
    linkGit: 'https://github.com/Webfre/nft-market',
    linkPage: 'https://webfre.github.io/nft-market/',
    imgUrl: dataImg.progect9,
    tags: ['React', 'Все'],
  },
  {
    name: 'Redux',
    title: ' / ',
    description: 'Redux',
    linkGit: '',
    linkPage: '',
    imgUrl: dataImg.redux,
    tags: ['Redux', 'Все'],
  },
];

export default filterWork;